name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃 저장소
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: Vite 프로젝트 빌드
        run: npm run build

      - name: GitHub Pages에 배포
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
